# Generated by Django 4.1.3 on 2023-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='read_by',
            field=models.CharField(default='10k', max_length=5),
        ),
    ]
