# Generated by Django 4.1.3 on 2023-02-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_slug_blog_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
    ]
